### ISSUE TITLE
Upload doesn't work?

### ISSUE THREAD

**Issue by elaw01887** [platevoltage/esp32-partition-calculator#1]
Uploading a valid "partitions.csv" from my desktop, doesn't seem to work.  No error message or anything, just nothing seems to happen.
[partitions.csv](https://github.com/user-attachments/files/17651399/partitions.csv)

**Comment by platevoltage** [comment]
Hello. I tested the application by uploading one of the .csv files that the was generated by the application itself with no issues. Would you mind sharing the .csv file that you are having issues with? It's possible that it uses a delimiter character that isn't expected.

**Comment by elaw01887** [comment]
Um… I’m not sure what’s up but it seems to be working now!  Though I’ve modified the partitions.csv recently.

 

I think it may just be me being stupid… I didn’t realize the tool read partitions.csv when it is first run, so when I tried importing that file and saw nothing on the screen change, I thought it wasn’t working.

 

Sorry, and I really appreciate you creating this tool!  Those files are not fun to work with and this really helps.

 

                Eric

**Comment by platevoltage** [comment]
I'm glad to hear that someone is using it! I created this because the only ESP partition calculator I could find was in excel spreadsheet form. I'll take a look at adding a little error handling for cases like this.
